{\rtf1\ansi\ansicpg1252\cocoartf2578
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red18\green19\blue24;\red247\green247\blue247;\red133\green85\blue4;
\red85\green93\blue101;\red85\green93\blue101;\red50\green94\blue238;\red18\green19\blue24;\red247\green247\blue247;
}
{\*\expandedcolortbl;;\cssrgb\c8627\c9804\c12157;\cssrgb\c97647\c97647\c97647;\cssrgb\c59608\c40784\c392;
\cssrgb\c40784\c43922\c47059;\cssrgb\c40784\c43922\c47059;\cssrgb\c25098\c47059\c94902;\cssrgb\c8627\c9804\c12157;\cssrgb\c97647\c97647\c97647;
}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs29\fsmilli14880 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 \
\pard\pardeftab720\partightenfactor0
\cf4 \cb1 \strokec4 version:\cf2 \cb3 \strokec2  \cf4 \cb1 \strokec4 0.0\cf2 \cb3 \strokec2 \
\cf4 \cb1 \strokec4 os:\cf2 \cb3 \strokec2  
\fs29\fsmilli14880 \cf5 \cb1 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 windows
\fs29\fsmilli14880 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 \
\pard\pardeftab720\partightenfactor0
\cf6 \cb1 \strokec6 # os: windows\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # During the Install deployment lifecycle event (which occurs between the \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   BeforeInstall and AfterInstall events), copy the specified files \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   in "source" starting from the root of the revision's file bundle \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   to "destination" on the Amazon EC2 instance.\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # Specify multiple "source" and "destination" pairs if you want to copy \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   from multiple sources or to multiple destinations.\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # If you are not copying any files to the Amazon EC2 instance, then remove the\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   "files" section altogether. A blank or incomplete "files" section\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   may cause associated deployments to fail.\cf2 \cb3 \strokec2 \
\pard\pardeftab720\partightenfactor0
\cf4 \cb1 \strokec4 files:\cf2 \cb3 \strokec2 \
  \cf7 \cb1 \strokec7 -\cf2 \cb3 \strokec2  \cf4 \cb1 \strokec4 source:\cf2 \cb3 \strokec2  /\
    \cf4 \cb1 \strokec4 destination: 
\fs29\fsmilli14880 \cf8 \cb9 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 /testDeployment1
\fs29\fsmilli14880 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 \
\
\
\pard\pardeftab720\partightenfactor0
\cf6 \cb1 \strokec6 # If you are not running any commands on the Amazon EC2 instance, then remove \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   the "hooks" section altogether. A blank or incomplete "hooks" section\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   may cause associated deployments to fail.\cf2 \cb3 \strokec2 \
\
\cf6 \cb1 \strokec6 # For each deployment lifecycle event, specify multiple "location" entries \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   if you want to run multiple scripts during that event.\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # You can specify "timeout" as the number of seconds to wait until failing the deployment \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   if the specified scripts do not run within the specified time limit for the \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   specified event. For example, 900 seconds is 15 minutes. If not specified, \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   the default is 1800 seconds (30 minutes).\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   Note that the maximum amount of time that all scripts must finish executing \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   for each individual deployment lifecycle event is 3600 seconds (1 hour). \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   Otherwise, the deployment will stop and CodeDeploy will consider the deployment\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   to have failed to the Amazon EC2 instance. Make sure that the total number of seconds \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   that are specified in "timeout" for all scripts in each individual deployment \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   lifecycle event does not exceed a combined 3600 seconds (1 hour).\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   you can specify "runas" in an event to\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   run as the specified user. For more information, see the documentation.\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   If you are deploying to Windows Server instances,\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   remove "runas" altogether.\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # If you do not want to run any commands during a particular deployment\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   lifecycle event, remove that event declaration altogether. Blank or \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   incomplete event declarations may cause associated deployments to fail.\cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 # During the ApplicationStop deployment lifecycle event, run the commands \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   in the script specified in "location" starting from the root of the \cf2 \cb3 \strokec2 \
\cf6 \cb1 \strokec6 #   revision's file bundle.\cf2 \cb3 \strokec2 \
}