const stanfordClubsList = [
  "550 Lasuen",
  "576 Alvarado",
  "610 Mayfield",
  "620 Mayfield",
  "650 Mayfield",
  "680 Lomita",
  "Acts 2 Christian Fellowship",
  "Adams",
  "ADMIN",
  "Adopt a Science Olympiad Team",
  "Adventist Christian Fellowship",
  "Afrobeats",
  "Aikido Association of Stanford",
  "Aisthesis, Stanford Undergraduate Journal of Classical Studies",
  "Akasma Bellydance",
  "Akwaaba Ghanaian Students Association",
  "Alliance",
  "Alpha Chi Sigma",
  "Alpha Epsilon Pi",
  "Alpha Kappa Alpha Sorority, Incorporated",
  "Alpha Kappa Delta Phi",
  "Alpha Kappa Psi",
  "Alpha Phi",
  "Alpha Phi Alpha",
  "Alternative Spring Break",
  "American Association of Petroleum Geologists, Stanford Student Chapter",
  "American Indian Science and Engineering Society",
  "American Institute of Aeronautics and Astronautics",
  "American Medical Student Association Stanford Premedical Chapter",
  "American Society for Engineering Education (Stanford Chapter)",
  "American Society of Civil Engineers",
  "Amnesty International, Stanford University Chapter",
  "Anime in the Arts",
  "Arab Student Association at Stanford",
  "Arbor Free Clinic",
  "Argentinos en Stanford",
  "Armed Forces Society",
  "Armenian Students Association",
  "Arroyo",
  "ArtX",
  "ASES: Stanford's Global Entrepreneurship Society",
  "Asha for Education- Stanford Chapter",
  "Asian American Activities Center",
  "Asian American Graduate Student Association",
  "Asian American Students' Association",
  "Asian American Theater Project",
  "Asian Pacific American Medical Student Association",
  "Asian Women's Alliance",
  "Associated Students of Stanford University (ASSU)",
  "Association of Chinese Students and Scholars at Stanford",
  "Association of Computing Machinery",
  "Association of Women Surgeons, Stanford Chapter",
  "ASSU Graduate Student Council",
  "ASSU Undergraduate Senate",
  "Bahai Association at Stanford",
  "Ballet Folklorico de Stanford",
  "Barrio Assistance",
  "Basmati Raas",
  "BEAM, Stanford Career Education",
  "Bechtel International Center",
  "BELGICA",
  "BioJam CoLABS",
  "Biological Interdisciplinary Open Maker Environment",
  "Biomedical Association for the Interest for Minority Students",
  "Biomedical Engineering Society",
  "BioSci Careers",
  "Black and Queer at Stanford",
  "Black Engineering Graduate Student Association",
  "Black Family Gathering Committee",
  "Black Graduate Students Association",
  "Black Graduation Committee",
  "Black in Computer Science at Stanford",
  "Black Men's Forum",
  "Black Pre-Law Society",
  "Black Recruitment Orientation Committee",
  "Black Student Union",
  "Blackstage",
  "BOB",
  "Branner",
  "Brazilian Students Association",
  "Bridges International",
  "Bridging the Gap",
  "Buddhist Community at Stanford",
  "Burbank",
  "Business Association of Stanford Entrepreneurial Students",
  "Caesura Journal",
  "Cambodian Student Association",
  "Cap and Gown",
  "Cardinal Ballet Company",
  "Cardinal Calypso",
  "Cardinal Free Clinics",
  "Cardinal Nights",
  "Cardinal Squares",
  "Cardinal Ventures",
  "Cardinal West Coast Swing",
  "Caribbean Students Association",
  "Casa Zapata",
  "Castaño",
  "Cedro",
  "Center for South Asia",
  "Center for Teaching and Learning: Academic Skills Resources",
  "Center for Teaching and Learning: Tutoring and Language Conversation Programs",
  "Central American Student Association",
  "Ceramics Club",
  "Challah for Hunger",
  "Chemical Engineering Graduate Students",
  "Chi Alpha Christian Fellowship",
  "Chi Omega",
  "Chinese Campus Evangelistic Fellowship",
  "Chinese Undergraduate Student Union",
  "Chinese Women Collective at Stanford",
  "Club Water Polo Team of Stanford",
  "CLUBSPORT",
  "Coaching Corps Stanford Chapter",
  "Code the Change",
  "Colombian Student Association",
  "Columbae",
  "Common Origins",
  "Computational Text Analysis in the Social Sciences Student Group",
  "Comunidad for Health Equity",
  "Confidential Support Team",
  "Cooking Healthy Eating Fresh",
  "Cornerstone",
  "Counseling and Psychological Services (CAPS)",
  "Counterpoint a cappella",
  "Cross-disciplinary Healthcare Innovation Partnership at Stanford",
  "Crothers",
  "CS+Social Good",
  "Dancebreak",
  "Data and Mapping for Society",
  "Delta Delta Delta",
  "Delta Kappa Epsilon Fraternity, Sigma Rho Chapter",
  "Delta Sigma Theta Sorority, Inc.",
  "Delta Tau Delta Fraternity",
  "Derechos",
  "Design for America",
  "Disability Studies Committee",
  "Doctors Without Borders Stanford Student Chapter",
  "Donner",
  "Dosti",
  "Down With Gravity",
  "DreamCatchers",
  "Dues/Membership Duration",
  "Durand",
  "Dutch@Stanford",
  "DV8",
  "Earthquake Engineering Research Institute (EERI) Stanford Chapter",
  "EAST",
  "East African Stanford Students Association",
  "East Florence Moore",
  "EBF",
  "Educational Studies Program",
  "El Centro Chicano y Latino",
  "Engineering Students for Diversity, Equity, and Inclusion",
  "Engineers for a Sustainable World - Stanford Chapter",
  "Environmental Health & Safety",
  "Episcopal - Lutheran Campus Ministry",
  "European Association at Stanford",
  "Everyday People",
  "EVGR-A",
  "Falun Dafa at Stanford",
  "Fascinate Publication",
  "FashionX",
  "Fellowship of Christian Athletes in Action",
  "FLIP: First-Generation, Low-Income Partnership",
  "Flying Treehouse",
  "Fraternity and Sorority Life (FSL)",
  "French Stanford Student Association",
  "Future Advancers of Science and Technology",
  "Girls Teaching Girls To Code",
  "Global Health Student Council",
  "Golden Spike Studios",
  "GradQ",
  "Graduate Admissions",
  "Graduate Catholic Student Association",
  "Graduate Life Office",
  "Graduate Mathematics Outreach Organization",
  "Graduate Multiracial Community",
  "Graduate Music Studies Forum",
  "Graduate Student Programming Board (GSPB)",
  "Graduate Students in Electrical Engineering",
  "Graduate Students of Applied Physics and Physics",
  "GSB Adam Smith Society",
  "GSB Aerospace Business Club",
  "GSB Africa Business Club",
  "GSB Artificial Intelligence Club",
  "GSB Arts, Media & Entertainment Club",
  "GSB Asian Business Student Association",
  "GSB Australia a​nd New Zealand Club",
  "GSB Basketball Club",
  "GSB Black Business Student Association",
  "GSB Business & Environment Club",
  "GSB Catholic Student Association",
  "GSB Challenge 4 Charity",
  "GSB Christians in Business",
  "GSB Consumer & Retail Club",
  "GSB Cybersecurity and Privacy Club",
  "GSB Education Club",
  "GSB Energy Club",
  "GSB Entrepreneur Club",
  "GSB Epicureans at the GSB",
  "GSB Europe Club",
  "GSB Finance & Investment Club",
  "GSB FinTech Club",
  "GSB First Generation and/or Low Income Club",
  "GSB Food & Agribusiness Club",
  "GSB Friends of TALK",
  "GSB Future of Cities",
  "GSB Future Of Mobility Club",
  "GSB Gaming Club",
  "GSB Gives Back",
  "GSB Golf Club",
  "GSB Government & Politics Club",
  "GSB Greater China Business Club",
  "GSB Healthcare Club",
  "GSB Hispanic Business Student Association",
  "GSB Improvisational Theater Troupe",
  "GSB India Club",
  "GSB Jewish Business Student Association",
  "GSB Latin American Student Association",
  "GSB Management Consulting Club",
  "GSB MBA Student Association",
  "GSB Middle East and North Africa Club",
  "GSB Midwest Club",
  "GSB MSx Student Association",
  "GSB Native Business Student Association",
  "GSB People People",
  "GSB PhD Association",
  "GSB Pride",
  "GSB Private Equity Club",
  "GSB Product Club",
  "GSB Real Estate Club",
  "GSB Search Fund Club",
  "GSB Show",
  "GSB Soccer Club",
  "GSB Social Impact Club",
  "GSB Sports Management Club",
  "GSB Student Engagement & Inclusion",
  "GSB Tech Club",
  "GSB Texas Club",
  "GSB Travel and Hospitality Club",
  "GSB Venture Capital Club",
  "GSB Veterans Club",
  "GSB Wellbeing Club",
  "GSB Wine Circle",
  "GSB Women in Management",
  "GSE Student Guild",
  "Habla",
  "Hammarskjold",
  "HD Crew",
  "Healing Strokes",
  "Health Education Lifetime Partnerships (HELP) for Kids",
  "Hellenic Association of Stanford",
  "Hermanas de Stanford",
  "Hillel@Stanford",
  "Hindu Students Association",
  "Hmong Student Union",
  "Hong Kong Student Association",
  "Hui o Na Moku",
  "Hume Center for Writing and Speaking",
  "Ideas Out Loud",
  "Inclusion, Community and Integrative Learning",
  "Indian Stanford Student Association",
  "Innovative Styles",
  "Institute for Operations Research and the Management Sciences",
  "Interfraternity Council",
  "International Policy Students Association",
  "International Socialist Organization - Stanford",
  "International Undergraduate Community",
  "Intersorority Council",
  "InterVarsity Christian Fellowship",
  "InterVarsity Graduate Christian Fellowship",
  "J Street U Stanford",
  "Jam Pac'd",
  "Japanese Student Union",
  "Jerry",
  "Jewish Student Association",
  "JKA Shotokan of Stanford",
  "Jujitsu Club",
  "Junipero",
  "Kairos",
  "Kaorihiva",
  "Kappa Alpha",
  "Kappa Alpha Psi Fraternity Incorporated",
  "Kappa Alpha Theta",
  "Kappa Kappa Gamma",
  "Kappa Sigma",
  "Kayumanggi",
  "Kids With Dreams",
  "Kimball",
  "Korean Bible Study and Koinonia, Stanford",
  "Korean-American Student Association",
  "Kurdish Association for Justice",
  "KZSU 90.1 FM",
  "L'Chayim Club: Chabad at Stanford",
  "La Familia de Stanford",
  "Lambda Phi Epsilon",
  "Lambda Theta Nu Sorority, Inc.",
  "Lantana",
  "Larkin",
  "Lathrop Learning Hub - The Tech Desk",
  "Latino Medical Student Association",
  "Latinos in Theater",
  "Latinos Unidos de Stanford",
  "Latter-day Saint Student Association",
  "Legacy Dance Team",
  "Legal Counseling Office",
  "Leland Quarterly",
  "Leland Stanford Junior University Marching Band",
  "LGBTQ-Meds",
  "Los Hermanos de Stanford",
  "Los Salseros de Stanford",
  "Malaysians at Stanford",
  "Management Science & Engineering Graduate Student Association",
  "March For Our Lives Stanford",
  "Mariachi Cardenal de Stanford",
  "Mars",
  "Mechanical Engineering Women's Group",
  "Medical Students with Disability and Chronic Illness",
  "Meier & Naranja",
  "Membership will end on 31 May 2023",
  "Membership will end on 31 May 2023",
  "Membership will end on 31 May 2023",
  "Men's Club Basketball",
  "Mexican Association of Graduate Students at Stanford",
  "Mind Over Money Financial Wellness",
  "MINT Magazine",
  "Mirrielees",
  "Mixed Company",
  "Modes of Knowing: Science, Religion, and Philosophy Club",
  "Movimiento Estudiantil Chicano de Aztlan",
  "Mua Lac Hong",
  "Multiracial Identified Community at Stanford",
  "Murray",
  "Music Enriching the Lives of Developing Youth",
  "Muslim Student Union",
  "Muwekma-Tah-Ruk",
  "Narnia",
  "National Organization for the Professional Advancement of Black Chemists and Chemical Engineers",
  "Ng House (Humanities)",
  "Nigerian Students Association (Naija)",
  "Noopur",
  "Norcliffe",
  "Nuestra Grad",
  "O-Tone",
  "Oasis Campus Ministry",
  "Off-Campus Fundraising (Corporate Sponsors)",
  "Off-Campus Fundraising (Corporate Sponsors)",
  "Office for Inclusion, Belonging, and Intergroup Communication",
  "Office for Military-Affiliated Communities",
  "Office for Religious & Spiritual Life",
  "Office of Accessible Education",
  "Office of Student Engagement",
  "Okada",
  "Organization of International Health",
  "Orthodox Christian Fellowship at Stanford",
  "Otero",
  "Out in Science, Technology, Engineering and Mathematics at Stanford",
  "Overseas Resource Center - Bechtel International Center",
  "Pakistanis at Stanford",
  "Palm Drive Records",
  "Parakaleo Christian Ministries",
  "Partners in Health | Engage",
  "Peer Technology Specialist Team",
  "People for Animal Welfare",
  "Perfusion: CPR Education and Advocacy",
  "Persian Student Association",
  "Phi Kappa Psi Fraternity",
  "Physics Undergraduate Women and Gender Minorities at Stanford",
  "Pi Beta Phi",
  "Pilipino American Student Union",
  "Pluto",
  "Political",
  "Potter",
  "Pre-Health FLI Student Association",
  "Primary Care Progress",
  "Product Hub of Stanford Students",
  "Professional Art Society of Stanford",
  "PULSE Magazine",
  "Queer in Government and Law",
  "Queer Student Resources",
  "Quiz Bowl Club",
  "Ram's Head Theatrical Society",
  "Ranchers and Farmers Society of Stanford",
  "Reformed University Fellowship at Stanford",
  "Restorative Film Collective",
  "Rinconada",
  "Ritmo!",
  "Robber Barons Sketch Comedy",
  "Robert Moore North (The Well)",
  "Robinson",
  "Roble",
  "Roth",
  "Ruedamores de Stanford",
  "Russian-speaking Student Association",
  "Russian, Eastern Europe, and Eurasian Studies Committee of Interested Scholars",
  "Sally Ride",
  "Saudi Arabian Students Organization",
  "Scandinavians at Stanford",
  "Schiff",
  "Schwab Learning Center",
  "Science Policy Group at Stanford",
  "Scientists Speak Up",
  "Sexual Health Peer Resources Center",
  "SHARE: Education Team",
  "Side by Side",
  "Sigma Alpha Epsilon",
  "Sigma Nu Fraternity, Beta Chi Chapter",
  "Sigma Phi Epsilon",
  "Sikh Students Association at Stanford",
  "Singaporeans at Stanford",
  "SIS (Arts Intensive, Sophomore College, IntroSems)",
  "SLS American Constitution Society",
  "SLS Antitrust Law and Policy Association",
  "SLS Asian Pacific Islander Law Student Association",
  "SLS BioLaw & Health Policy Society",
  "SLS Black Law Students Association",
  "SLS Blockchain Law and Information Society",
  "SLS China Law & Policy Association",
  "SLS Christian Fellowship",
  "SLS Criminal Law Society",
  "SLS Disability and Mental Health Network at Stanford",
  "SLS Drama Society",
  "SLS Effective Altruism",
  "SLS Election Law Project",
  "SLS Energy and Infrastructure Club",
  "SLS Entrepreneurship Club",
  "SLS Environmental Law Society",
  "SLS Federalist Society",
  "SLS First Generation and Low-Income Professionals",
  "SLS First Person",
  "SLS If/When/How",
  "SLS International Arbitration Association",
  "SLS International Law Society",
  "SLS International Refugee Assistance Project",
  "SLS J. Reuben Clark Society",
  "SLS JD/MBA Club",
  "SLS Jewish Law Student Association",
  "SLS Law & Political Economy",
  "SLS Law Students for Gender Violence Prevention",
  "SLS Middle Eastern and South Asian Law Students Association",
  "SLS Muslim Law Student Association",
  "SLS National Lawyers Guild",
  "SLS Native American Law Student Association",
  "SLS Older and Wiser Law Students",
  "SLS OUTLAW",
  "SLS Shaking the Foundations Conference",
  "SLS Stanford Advocates for Immigrants' Rights",
  "SLS Stanford Artifical Intelligence Law Society",
  "SLS Stanford Critical Legal Studies",
  "SLS Stanford Entertainment and Sports Law Association",
  "SLS Stanford Human Rights Law Association",
  "SLS Stanford Intellectual Property Association",
  "SLS Stanford Latinx Law Students Association",
  "SLS Stanford Law and Technology Association",
  "SLS Stanford Law and Wine Society",
  "SLS Stanford Law Association",
  "SLS Stanford Law Democrats",
  "SLS Stanford Law Private Practice Association",
  "SLS Stanford Law School Mock Trial Team",
  "SLS Stanford Law Veterans Organization",
  "SLS Stanford National Security and the Law Society",
  "SLS Stanford Plaintiffs' Lawyers Association",
  "SLS Stanford Prisoner Advocacy and Resources Coalition",
  "SLS Stanford Program in Law and Society",
  "SLS Stanford Public Interest Law Foundation",
  "SLS StreetLaw",
  "SLS Student Affairs",
  "SLS Student Animal Legal Defense Fund",
  "SLS Tax Club",
  "SLS Transfers of Stanford Law",
  "SLS Women in Politics and Public Service",
  "SLS Women of Color Collective",
  "SLS Women of Stanford Law",
  "SLS Youth and Education Advocates of Stanford",
  "SMS First-Generation and/or Low-Income at Stanford University School of Medicine",
  "Society for Industrial and Applied Mathematics (SIAM), Stanford Student Chapter",
  "Society for International Affairs at Stanford",
  "Society for the Advancement of Chicano/Latinos and Native Americans in Science",
  "Society of Black Scientists and Engineers",
  "Society of Latinx Engineers",
  "Society of Petroleum Engineers, Stanford Student Chapter",
  "Society of Women Engineers",
  "Soto",
  "Speakers Bureau",
  "Spicmacay",
  "Stand Up, D Comedy Club",
  "Stanford ACM SIGGRAPH Student Chapter",
  "Stanford Advanced Degree Candidate Consulting Club",
  "Stanford Aerobics and Yoga",
  "Stanford African Students Association",
  "Stanford Alpine Club",
  "Stanford Alpine Project",
  "Stanford Alpine Ski Team",
  "Stanford Alumni Association",
  "Stanford Alzheimer's Alliance",
  "Stanford Amateur Radio Club",
  "Stanford American Civil Liberties Union",
  "Stanford American Indian Organization",
  "Stanford American Indigenous Medical Students",
  "Stanford Anthology for Youth",
  "Stanford Applied Cybersecurity",
  "Stanford Arab Leadership and Advocacy in Medicine",
  "Stanford Archery Program",
  "Stanford Artificial Intelligence Group",
  "Stanford Arts (VPA)",
  "Stanford Arts Review",
  "Stanford Asian American Activism Committee",
  "Stanford Association of Students for Sexual Assault Prevention (Stanford ASAP)",
  "Stanford Astronomical Society",
  "Stanford Athletics",
  "Stanford Australians and New Zealanders",
  "Stanford Austria Club",
  "Stanford Axe Committee",
  "Stanford Badminton Club",
  "Stanford Bhakti Yoga Club",
  "Stanford Bhangra Team",
  "Stanford Biosciences Student Association",
  "Stanford Birdwatching Club",
  "Stanford Black Bioscience Organization",
  "Stanford Black Gender Marginalized Collective",
  "Stanford Black Pre-Medical Organization",
  "Stanford Blockchain Club",
  "Stanford Breakfast Club",
  "Stanford Busking Club",
  "Stanford Canadian Club",
  "Stanford Capoeira",
  "Stanford Catalan Association",
  "Stanford Ceili Dance",
  "Stanford Chamber Chorale",
  "Stanford Chaparral",
  "Stanford Chapter of American Medical Association - Medical Student Section",
  "Stanford Cheer",
  "Stanford Chess Club",
  "Stanford Chinese Dance",
  "Stanford Chinese Music Ensemble",
  "Stanford Chinese Sing",
  "Stanford Christian Students",
  "Stanford Classics in Theater",
  "Stanford Climate and Health",
  "Stanford Climbing",
  "Stanford Club Baseball",
  "Stanford Club Ice Hockey",
  "Stanford Club of Spain",
  "Stanford Club Sports",
  "Stanford Club Swimming",
  "Stanford Club Tennis",
  "Stanford Club Triathlon Team",
  "Stanford Collaborative Orchestra",
  "Stanford College Diabetes Network",
  "Stanford College Republicans",
  "Stanford Community Gardens",
  "Stanford Complexity Group",
  "Stanford Concert Network",
  "Stanford Consulting",
  "Stanford Cooking Society",
  "Stanford Creative Writing Society",
  "Stanford Cycling",
  "Stanford Dance Marathon",
  "Stanford DanceSport",
  "Stanford Debate Society",
  "Stanford Democrats",
  "Stanford Digital Shapers",
  "Stanford Disability Alliance",
  "Stanford DJ Society",
  "Stanford Dominican Association",
  "Stanford Drag Troupe",
  "Stanford Dragon Boat",
  "Stanford Economics Association",
  "Stanford Education Technology Society",
  "Stanford Effective Altruism",
  "Stanford Energy Club",
  "Stanford Entrepreneurs for Latin America",
  "Stanford Equestrian Team",
  "Stanford Ethiopian and Eritrean Student Association",
  "Stanford Etz Chaim",
  "Stanford Figure Skating Club",
  "Stanford Film Society",
  "Stanford Finance",
  "Stanford Fleet Street Singers",
  "Stanford FLI Office",
  "Stanford Fly Fishing and Tying Club",
  "Stanford Food Recovery",
  "Stanford Game^2 Theory Club",
  "Stanford Gaming Society",
  "Stanford Genetic Counseling Student Interest Group",
  "Stanford German Student Association",
  "Stanford Gleaning Project",
  "Stanford Global Studies",
  "Stanford Golf League",
  "Stanford Gospel Choir",
  "Stanford Graduate Society of Women Engineers",
  "Stanford Grappling Club",
  "Stanford Gregorian Society",
  "Stanford Harmonics",
  "Stanford Health Innovations in Future Technologies",
  "Stanford Health Justice Coalition",
  "Stanford Hermanas in STEM",
  "Stanford Humanities Review",
  "Stanford ignitED",
  "Stanford Improvisors",
  "Stanford In Government",
  "Stanford India Association",
  "Stanford India Economic and Policy Club",
  "Stanford Indonesian Student Union",
  "Stanford Institute of Electrical and Electronics Engineers",
  "Stanford International Justice Mission",
  "Stanford International Security Undergraduate Network",
  "Stanford Irish Association",
  "Stanford Israel Association",
  "Stanford Italian Society",
  "Stanford Japanese Association",
  "Stanford Jazz Orchestra",
  "Stanford Jewish Queers",
  "Stanford Judo Club Team",
  "Stanford Jump Rope",
  "Stanford Kayak Club",
  "Stanford Kendo Club",
  "Stanford Kenpo Karate Association",
  "Stanford Latino",
  "Stanford Latinx Business Association",
  "Stanford LGBT Business Alliance",
  "Stanford Libraries",
  "Stanford Light Opera Company",
  "Stanford Lion Dance",
  "Stanford Marketing Group",
  "Stanford Martial Arts Program",
  "Stanford Materials Research Society",
  "Stanford Medical Christian Fellowship",
  "Stanford Medical Humanities Club",
  "Stanford Medical Students Association",
  "Stanford Medicine Arts Collective",
  "Stanford Men's Club Soccer Team",
  "Stanford Men's Lacrosse",
  "Stanford Men's Rugby",
  "Stanford Men's Ultimate Team",
  "Stanford Men's Volleyball Club",
  "Stanford Mendicants",
  "Stanford Mental Health Outreach",
  "Stanford Middle East Ensemble",
  "Stanford Mock Trial",
  "Stanford Music + Mentorship",
  "Stanford Muslim Medical Association",
  "Stanford National Association for the Advancement of Colored People",
  "Stanford Native American Graduate Students",
  "Stanford NeuroX",
  "Stanford Oceans Society",
  "Stanford Otolaryngology Interest Group",
  "Stanford Outdoor Outreach Program",
  "Stanford Outdoors",
  "Stanford Pen People",
  "Stanford Physical Medicine and Rehabilitation Interest Group",
  "Stanford Planned Parenthood Generation Action",
  "Stanford Poetry Society",
  "Stanford Polish Student Association",
  "Stanford Political Union",
  "Stanford Politics",
  "Stanford Polo Club",
  "Stanford Polymer Collective",
  "Stanford Powwow",
  "Stanford Practical Ethics Club",
  "Stanford Pre-Business Association",
  "Stanford Pre-Law Society",
  "Stanford Pre-Medical Asian Pacific American Medical Student Association",
  "Stanford Premedical Association",
  "Stanford Public Interest Technology Lab",
  "Stanford Quantum Computing Association",
  "Stanford Queer & Asian",
  "Stanford Quidditch",
  "Stanford Raagapella",
  "Stanford Real Estate Club",
  "Stanford Recreation & Wellness",
  "Stanford Robotics Club",
  "Stanford Roots",
  "Stanford Running Club",
  "Stanford Running Club",
  "Stanford Science Penpals",
  "Stanford Science, Technology, Engineering, Arts, & Mathematics",
  "Stanford Shakespeare Company",
  "Stanford Smart Woman Securities",
  "Stanford Social Entrepreneurial Student's Association",
  "Stanford Society for Latin American Politics",
  "Stanford Society of Pediatric Psychology",
  "Stanford Solar Car Project",
  "Stanford South Asian Society",
  "Stanford Sphere",
  "Stanford Spikeball Roundnet Club",
  "Stanford Spoken Word Collective",
  "Stanford Sports Analytics Club",
  "Stanford Squash Men's Intercollegiate Team",
  "Stanford Storyboard Club",
  "Stanford Student Biodesign & Biopharma",
  "Stanford Student Biotechnology Group",
  "Stanford Student Space Initiative",
  "Stanford Students Environmental Consulting",
  "Stanford Students for Housing Justice",
  "Stanford Students for Justice in Palestine",
  "Stanford Students for Life",
  "Stanford Students for Queer Liberation",
  "Stanford Students in Applied Research",
  "Stanford Students In Entertainment",
  "Stanford Swing Dancers",
  "Stanford Symbolic Systems Society",
  "Stanford Symphony Orchestra",
  "Stanford Synapse: Brain Injury Support Group",
  "Stanford Table Tennis Club",
  "Stanford Taekwondo",
  "Stanford Taiko",
  "Stanford Taiwanese Student Association",
  "Stanford Tango Club",
  "Stanford Theater Laboratory",
  "Stanford Transfers Network",
  "Stanford Turkish Student Association",
  "Stanford Turning Point USA",
  "Stanford Undergraduate Hospice and Palliative Care",
  "Stanford Undergraduate Materials Society (SUMS)",
  "Stanford Undergraduate Neuroscience Society",
  "Stanford Undergraduate Psychology Association",
  "Stanford Undergraduate Research Association",
  "Stanford Undergraduate Research Journal",
  "Stanford Undergraduate Veterans Association",
  "Stanford Undergraduates in Mechanical Engineering",
  "Stanford University Mathematical Organization",
  "Stanford University PA Student Association",
  "Stanford University Physics Society",
  "Stanford University Postdoctoral Association",
  "Stanford University Wing Chun Student Association",
  "Stanford Unmanned Aerial Vehicle Engineers, Entrepreneurs, and Enthusiasts",
  "Stanford Uruguayan Students Association",
  "Stanford Venture Capital Club",
  "Stanford Video Game Association",
  "Stanford Vietnamese Student Association",
  "Stanford Wind Symphony",
  "Stanford Wine Society",
  "Stanford Women Association of Physician-Scientists",
  "Stanford Women in Business",
  "Stanford Women in Design",
  "Stanford Women in Earth Sciences",
  "Stanford Women in Finance",
  "Stanford Women in Fluid Dynamics",
  "Stanford Women in Law",
  "Stanford Women in Medicine",
  "Stanford Women in Politics",
  "Stanford Women's Club Lacrosse",
  "Stanford Women's Club Soccer",
  "Stanford Women's Club Volleyball",
  "Stanford Women's Rugby",
  "Stanford Women's Ultimate",
  "Stanford Womxn in Cannabis",
  "Stanford Womxn in Comedy",
  "Stanford Worldbuilding Activities Network",
  "Stanford Wushu Club",
  "Stanford XR",
  "Stanford Young Democratic Socialists of America",
  "Stanford Zen Society",
  "Stanford Zumba",
  "Storey",
  "Strategies for Ecology Education, Diversity and Sustainability, Stanford Chapter",
  "Student Alliance for Justice in Education",
  "Student and Labor Alliance",
  "Student Immigrant Empowerment Project at Stanford",
  "Student Interest Group in Neurology",
  "Student National Medical Association",
  "Student Services Center",
  "Students Against Eating Disorders",
  "Students for a Sustainable Stanford",
  "Students for Alternatives to Militarism",
  "Suites",
  "Swingtime",
  "Synergy",
  "Taiwanese Cultural Society",
  "Talisman",
  "tapTH@T",
  "Tau Beta Pi",
  "Team HBV",
  "Terra",
  "Testimony A Cappella",
  "Thai Student Association",
  "The Black Feminist Collective",
  "The Blackprint: Building Black Business Leaders and Entrepreneurs",
  "The Bridge Peer Counseling Center",
  "The Charles R. Blyth Fund",
  "The Dish on Science",
  "The Forest",
  "The Humor Club",
  "The Komm Collective",
  "The Science Bus",
  "The Social Project",
  "The Stanford Bicycle Project",
  "The Stanford Daily",
  "The Stanford Flipside",
  "The Stanford Fund",
  "The Stanford Happiness Collective",
  "The Stanford Libertarians",
  "The Stanford Optical Society",
  "The Stanford Review",
  "The Stanford Storytelling Project",
  "The Word: The Stanford Journal of Student Hiphop Research",
  "Tibetan Student Union",
  "Toyon",
  "Traction Modern Dance Company",
  "Trancos",
  "Traveling Trees",
  "TreeHacks",
  "Tresidder Meeting Services",
  "Twain",
  "Tzu Chi Collegiate Association, Stanford Chapter",
  "Ujamaa",
  "Undergraduate Catholic Student Association",
  "Undergraduate Chinese American Association",
  "Unitarian Universalists of Stanford",
  "United Students for Veterans' Health",
  "Unscripted Playhouse of Stanford",
  "Untitled Journal",
  "Venezuelan Student Association",
  "Veritas@Stanford",
  "Viennese Ball Committee",
  "Vitruvian Leaders Series",
  "Volunteers In Latin America",
  "Vox Clara: A Journal of Christian Thought at Stanford",
  "We Continue: Suicide Prevention Empowerment",
  "Weiland Health Initiative",
  "Well-Being at Stanford",
  "West Florence Moore",
  "West Lagunita",
  "Will end at Graduation",
  "Will end at Graduation",
  "Women and Medicine",
  "Women and Youth Supporting Each Other",
  "Women in Aeronautics and Astronautics",
  "Women in Computer Science",
  "Women in Electrical Engineering",
  "Women in Mathematics, Statistics, and Computational Engineering",
  "Women's Club Basketball",
  "Womxn's Coalition",
  "World Peace Buddhists",
  "Xanadu",
  "XTRM",
  "Yost",
  "Young Life Stanford",
  "ZAP",
];

module.exports = { stanfordClubsList };
